# Generated by Django 2.0.3 on 2018-03-20 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maximum_no_cars', models.IntegerField(default=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('([A-Za-z]{3}\\-\\d{3}[A-Za-z]{2})', 'Plate Number are in the format ABC-123DE')])),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True)),
                ('fee_paid', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('0', 'parked'), ('1', 'exited')], default='parked', max_length=7)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall', to='ticketingapp.Mall')),
            ],
        ),
        migrations.AddIndex(
            model_name='parkingticket',
            index=models.Index(fields=['plate_number'], name='ticketingap_plate_n_972dac_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingticket',
            index=models.Index(fields=['mall'], name='ticketingap_mall_id_eb47cc_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingticket',
            index=models.Index(fields=['plate_number', 'mall'], name='ticketingap_plate_n_c58aee_idx'),
        ),
    ]
