# Generated by Django 2.0.3 on 2018-03-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingticket',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
