# Generated by Django 2.0.3 on 2018-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0002_auto_20180320_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
