# Generated by Django 2.0.3 on 2018-03-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0003_parkingticket_checkout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('malls', models.ManyToManyField(related_name='tenants', to='ticketingapp.Mall')),
            ],
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkingtickets', to='ticketingapp.Mall'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='status',
            field=models.CharField(choices=[('parked', 'parked'), ('exited', 'exited')], default='parked', max_length=7),
        ),
    ]
