# Generated by Django 2.0.3 on 2018-03-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0004_auto_20180322_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_parkingtickets', to='ticketingapp.Tenant'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['name'], name='ticketingap_name_88192a_idx'),
        ),
    ]
