# Generated by Django 2.0.3 on 2018-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0005_auto_20180322_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='malls',
            field=models.ManyToManyField(blank=True, related_name='tenants', to='ticketingapp.Mall'),
        ),
    ]
