# Generated by Django 2.0.3 on 2018-07-29 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketingapp', '0007_auto_20180327_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='malls', to=settings.AUTH_USER_MODEL),
        ),
    ]
