# Generated by Django 2.1.4 on 2018-12-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0008_mall_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='malls',
        ),
        migrations.AddField(
            model_name='tenant',
            name='malls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='ticketingapp.Mall'),
        ),
    ]
