# Generated by Django 2.1.4 on 2018-12-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0009_change_tenant_to_one_to_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='charge_per_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mall',
            name='first_thirty_free',
            field=models.BooleanField(default=False),
        ),
    ]
