# Generated by Django 2.1.4 on 2018-12-22 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0010_add_new_fields_to_mall'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('([A-Za-z]{3}\\-\\d{3}[A-Za-z]{2})', 'Plate Number are in the format ABC-123DE')])),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='ticketingapp.Tenant')),
            ],
        ),
    ]
