# Generated by Django 2.1.4 on 2018-12-24 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # For SQLite on local testing
    # atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketingapp', '0011_create_tenant_cars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mall',
            new_name='Park',
        ),
        migrations.RemoveIndex(
            model_name='parkingticket',
            name='ticketingap_mall_id_eb47cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingticket',
            name='ticketingap_plate_n_c58aee_idx',
        ),
        migrations.RenameField(
            model_name='parkingticket',
            old_name='mall',
            new_name='park',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='malls',
            new_name='parks',
        ),
        migrations.AddIndex(
            model_name='parkingticket',
            index=models.Index(fields=['park'], name='ticketingap_park_id_ffc12a_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingticket',
            index=models.Index(fields=['plate_number', 'park'], name='ticketingap_plate_n_bbc9ed_idx'),
        ),
    ]
