# Generated by Django 2.1.4 on 2018-12-24 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketingapp', '0014_rename_tenant_parks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
