# Generated by Django 2.1.4 on 2018-12-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0015_create_tenant_admin_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='charge_per_min',
            field=models.FloatField(default=0),
        ),
    ]
